2023-08-12 15:39:56,191 INFO [django.utils.autoreload:668] autoreload 13 140596564065096 Watching for file changes with StatReloader
2023-08-12 15:40:00,460 INFO [django.utils.autoreload:266] autoreload 13 140596564065096 /application/app/services/__init__.py changed, reloading.
2023-08-12 15:40:03,407 INFO [django.utils.autoreload:668] autoreload 15 139978346896200 Watching for file changes with StatReloader
2023-08-12 15:41:21,214 WARNING [django.request:241] log 15 139978280000312 Not Found: /entities/organizations
2023-08-12 15:42:19,120 WARNING [django.request:241] log 15 139978280000312 Unauthorized: /app/entities
2023-08-12 15:42:23,079 WARNING [django.request:241] log 15 139978280000312 Unauthorized: /accounts/login/token/
2023-08-12 15:44:19,181 INFO [core.utils.seed_dev:29] seed_dev 24 140043363179336 INICIANDO CARGA DE DADOS
2023-08-12 15:44:19,758 INFO [core.utils.seed_dev:33] seed_dev 24 140043363179336 CARGA DE DADOS FINALIZADA
2023-08-12 15:44:42,459 ERROR [app.api.ViewEntity:25] ViewEntity 15 139978280041272 ViewEntity (post) error ServiceEntity.create() takes 1 positional argument but 2 were given
2023-08-12 15:44:42,461 ERROR [django.request:241] log 15 139978280041272 Internal Server Error: /app/entities
2023-08-12 15:45:24,536 INFO [django.utils.autoreload:266] autoreload 15 139978346896200 /application/app/api/ViewEntity.py changed, reloading.
2023-08-12 15:45:26,566 INFO [django.utils.autoreload:668] autoreload 31 140181096110920 Watching for file changes with StatReloader
2023-08-12 15:45:42,407 INFO [django.utils.autoreload:266] autoreload 31 140181096110920 /application/app/api/ViewEntity.py changed, reloading.
2023-08-12 15:45:44,476 INFO [django.utils.autoreload:668] autoreload 33 140113968528200 Watching for file changes with StatReloader
2023-08-12 15:45:51,708 INFO [django.utils.autoreload:266] autoreload 33 140113968528200 /application/app/api/ViewEntity.py changed, reloading.
2023-08-12 15:45:53,989 INFO [django.utils.autoreload:668] autoreload 35 140309466508104 Watching for file changes with StatReloader
2023-08-12 15:45:55,106 ERROR [django.request:241] log 35 140309399804728 Internal Server Error: /app/entities
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ServiceEntity is not JSON serializable
2023-08-12 15:46:12,510 INFO [django.utils.autoreload:266] autoreload 35 140309466508104 /application/app/api/ViewEntity.py changed, reloading.
2023-08-12 15:46:15,271 INFO [django.utils.autoreload:668] autoreload 38 140405223500616 Watching for file changes with StatReloader
2023-08-12 15:46:19,845 ERROR [django.request:241] log 38 140405156678456 Internal Server Error: /app/entities
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ServiceEntity is not JSON serializable
2023-08-12 15:46:41,468 INFO [django.utils.autoreload:266] autoreload 38 140405223500616 /application/app/api/ViewEntity.py changed, reloading.
2023-08-12 15:46:43,571 INFO [django.utils.autoreload:668] autoreload 41 140449162951496 Watching for file changes with StatReloader
2023-08-12 15:46:47,214 ERROR [app.api.ViewEntity:25] ViewEntity 41 140449096125240 ViewEntity (post) error Error on create Organization 'category'
2023-08-12 15:46:47,217 ERROR [django.request:241] log 41 140449096125240 Internal Server Error: /app/entities
2023-08-12 15:47:15,934 ERROR [app.api.ViewEntity:25] ViewEntity 41 140449096125240 ViewEntity (post) error Error on create Organization EntityCategory matching query does not exist.
2023-08-12 15:47:15,935 ERROR [django.request:241] log 41 140449096125240 Internal Server Error: /app/entities
2023-08-12 15:47:45,397 INFO [django.utils.autoreload:266] autoreload 41 140449162951496 /application/app/repositories/EntityCategoryRepository.py changed, reloading.
2023-08-12 15:47:47,359 INFO [django.utils.autoreload:668] autoreload 44 139931965901640 Watching for file changes with StatReloader
2023-08-12 15:47:49,398 ERROR [app.api.ViewEntity:25] ViewEntity 44 139931899165496 ViewEntity (post) error Error on create Organization Cannot assign "(<EntityCategory: EMPRESA>, True)": "Entity.category" must be a "EntityCategory" instance.
2023-08-12 15:47:49,400 ERROR [django.request:241] log 44 139931899165496 Internal Server Error: /app/entities
2023-08-12 15:48:45,291 INFO [django.utils.autoreload:266] autoreload 44 139931965901640 /application/app/repositories/EntityCategoryRepository.py changed, reloading.
2023-08-12 15:48:47,309 INFO [django.utils.autoreload:668] autoreload 47 139828600503112 Watching for file changes with StatReloader
2023-08-12 15:49:10,622 WARNING [django.request:241] log 47 139828533680952 Not Found: /entities/organizations
2023-08-12 15:49:18,985 ERROR [app.api.ViewEntity:35] ViewEntity 47 139828533680952 ViewEntity (get) error 'ViewEntity' object has no attribute 'service'
2023-08-12 15:49:18,987 ERROR [django.request:241] log 47 139828533680952 Internal Server Error: /app/entities
2023-08-12 15:49:48,980 INFO [django.utils.autoreload:266] autoreload 47 139828600503112 /application/app/api/ViewEntity.py changed, reloading.
2023-08-12 15:49:51,148 INFO [django.utils.autoreload:668] autoreload 50 139712776727368 Watching for file changes with StatReloader
2023-08-12 15:50:03,201 ERROR [app.api.ViewEntity:35] ViewEntity 50 139712709905208 ViewEntity (get) error 'address'
2023-08-12 15:50:03,203 ERROR [django.request:241] log 50 139712709905208 Internal Server Error: /app/entities
2023-08-12 15:51:45,389 INFO [django.utils.autoreload:266] autoreload 50 139712776727368 /application/app/services/ServiceEntity.py changed, reloading.
2023-08-12 15:51:47,338 INFO [django.utils.autoreload:668] autoreload 53 140551312902984 Watching for file changes with StatReloader
2023-08-12 15:51:49,548 ERROR [app.api.ViewEntity:35] ViewEntity 53 140551246166840 ViewEntity (get) error Error on create Organization 'name'
2023-08-12 15:51:49,549 ERROR [django.request:241] log 53 140551246166840 Internal Server Error: /app/entities
2023-08-12 15:52:21,588 INFO [django.utils.autoreload:266] autoreload 53 140551312902984 /application/app/api/ViewEntity.py changed, reloading.
2023-08-12 15:52:23,667 INFO [django.utils.autoreload:668] autoreload 56 140715034901320 Watching for file changes with StatReloader
2023-08-12 15:52:26,957 ERROR [app.api.ViewEntity:35] ViewEntity 56 140714968062776 ViewEntity (get) error Erro on get Organization 'module' object is not callable
2023-08-12 15:52:26,960 ERROR [django.request:241] log 56 140714968062776 Internal Server Error: /app/entities
2023-08-12 15:53:17,339 INFO [django.utils.autoreload:266] autoreload 56 140715034901320 /application/app/services/ServiceEntity.py changed, reloading.
2023-08-12 15:53:19,522 INFO [django.utils.autoreload:668] autoreload 59 139763053951816 Watching for file changes with StatReloader
2023-08-12 15:54:37,068 INFO [django.utils.autoreload:266] autoreload 59 139763053951816 /application/app/services/ServiceEntity.py changed, reloading.
2023-08-12 15:54:41,060 INFO [django.utils.autoreload:668] autoreload 61 140531308890952 Watching for file changes with StatReloader
2023-08-12 15:54:42,609 ERROR [app.api.ViewEntity:35] ViewEntity 61 140531242208056 ViewEntity (get) error Erro on get Entities 'module' object is not callable
2023-08-12 15:54:42,612 ERROR [django.request:241] log 61 140531242208056 Internal Server Error: /app/entities
2023-08-12 15:56:08,988 INFO [django.utils.autoreload:266] autoreload 61 140531308890952 /application/app/services/ServiceEntity.py changed, reloading.
2023-08-12 15:56:11,688 INFO [django.utils.autoreload:668] autoreload 64 140279919057736 Watching for file changes with StatReloader
2023-08-12 15:56:17,023 INFO [django.utils.autoreload:266] autoreload 64 140279919057736 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 15:56:19,755 INFO [django.utils.autoreload:668] autoreload 66 139912908819272 Watching for file changes with StatReloader
2023-08-12 15:56:24,654 ERROR [app.api.ViewEntity:35] ViewEntity 66 139912841911096 ViewEntity (get) error Erro on get Entities 'module' object is not callable
2023-08-12 15:56:24,656 ERROR [django.request:241] log 66 139912841911096 Internal Server Error: /app/entities
2023-08-12 15:57:49,240 INFO [django.utils.autoreload:266] autoreload 66 139912908819272 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 15:57:51,373 INFO [django.utils.autoreload:668] autoreload 69 140425501080392 Watching for file changes with StatReloader
2023-08-12 15:57:59,851 INFO [django.utils.autoreload:266] autoreload 69 140425501080392 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 15:58:02,751 INFO [django.utils.autoreload:668] autoreload 71 140402545834824 Watching for file changes with StatReloader
2023-08-12 16:00:36,386 INFO [django.utils.autoreload:266] autoreload 71 140402545834824 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:00:38,559 INFO [django.utils.autoreload:668] autoreload 73 139688875539272 Watching for file changes with StatReloader
2023-08-12 16:01:31,908 INFO [django.utils.autoreload:266] autoreload 73 139688875539272 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:01:33,942 INFO [django.utils.autoreload:668] autoreload 75 140306304441160 Watching for file changes with StatReloader
2023-08-12 16:01:44,791 INFO [django.utils.autoreload:266] autoreload 75 140306304441160 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:01:47,106 INFO [django.utils.autoreload:668] autoreload 77 140549851339592 Watching for file changes with StatReloader
2023-08-12 16:01:53,591 ERROR [app.api.ViewEntity:35] ViewEntity 77 140549784460088 ViewEntity (get) error Erro on get Entities 'module' object is not callable
2023-08-12 16:01:53,593 ERROR [django.request:241] log 77 140549784460088 Internal Server Error: /app/entities
2023-08-12 16:01:59,141 INFO [django.utils.autoreload:266] autoreload 77 140549851339592 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:02:01,527 INFO [django.utils.autoreload:668] autoreload 80 140682940050248 Watching for file changes with StatReloader
2023-08-12 16:02:03,118 ERROR [app.api.ViewEntity:35] ViewEntity 80 140682873379640 ViewEntity (get) error Erro on get Entities 'module' object is not callable
2023-08-12 16:02:03,120 ERROR [django.request:241] log 80 140682873379640 Internal Server Error: /app/entities
2023-08-12 16:02:29,795 INFO [django.utils.autoreload:266] autoreload 80 140682940050248 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:02:32,384 INFO [django.utils.autoreload:668] autoreload 83 139838116547400 Watching for file changes with StatReloader
2023-08-12 16:02:34,092 ERROR [app.api.ViewEntity:35] ViewEntity 83 139838049782584 ViewEntity (get) error Erro on get Entities 'module' object is not callable
2023-08-12 16:02:34,094 ERROR [django.request:241] log 83 139838049782584 Internal Server Error: /app/entities
2023-08-12 16:03:10,168 INFO [django.utils.autoreload:266] autoreload 83 139838116547400 /application/app/services/ServiceEntity.py changed, reloading.
2023-08-12 16:03:12,391 INFO [django.utils.autoreload:668] autoreload 86 139880945187656 Watching for file changes with StatReloader
2023-08-12 16:03:13,688 ERROR [app.api.ViewEntity:35] ViewEntity 86 139880878447416 ViewEntity (get) error Erro on get Entities When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2023-08-12 16:03:13,690 ERROR [django.request:241] log 86 139880878447416 Internal Server Error: /app/entities
2023-08-12 16:03:45,512 INFO [django.utils.autoreload:266] autoreload 86 139880945187656 /application/app/services/ServiceEntity.py changed, reloading.
2023-08-12 16:03:47,681 INFO [django.utils.autoreload:668] autoreload 89 139706241133384 Watching for file changes with StatReloader
2023-08-12 16:04:15,978 ERROR [app.api.ViewEntity:35] ViewEntity 89 139706174315320 ViewEntity (get) error Erro on get Entities ListSerializer.to_representation() missing 1 required positional argument: 'data'
2023-08-12 16:04:15,980 ERROR [django.request:241] log 89 139706174315320 Internal Server Error: /app/entities
2023-08-12 16:04:27,713 INFO [django.utils.autoreload:266] autoreload 89 139706241133384 /application/app/services/ServiceEntity.py changed, reloading.
2023-08-12 16:04:29,733 INFO [django.utils.autoreload:668] autoreload 92 140681260018504 Watching for file changes with StatReloader
2023-08-12 16:09:52,602 INFO [django.utils.autoreload:266] autoreload 92 140681260018504 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:09:54,640 INFO [django.utils.autoreload:668] autoreload 95 140708041005896 Watching for file changes with StatReloader
2023-08-12 16:11:57,428 INFO [django.utils.autoreload:266] autoreload 95 140708041005896 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:11:59,358 INFO [django.utils.autoreload:668] autoreload 97 140018030332744 Watching for file changes with StatReloader
2023-08-12 16:12:57,195 INFO [django.utils.autoreload:266] autoreload 97 140018030332744 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:12:59,191 INFO [django.utils.autoreload:668] autoreload 99 140344200641352 Watching for file changes with StatReloader
2023-08-12 16:13:55,169 INFO [django.utils.autoreload:266] autoreload 99 140344200641352 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:13:57,287 INFO [django.utils.autoreload:668] autoreload 101 139984847649608 Watching for file changes with StatReloader
2023-08-12 16:16:09,840 INFO [django.utils.autoreload:266] autoreload 101 139984847649608 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:16:11,908 INFO [django.utils.autoreload:668] autoreload 103 139625083448136 Watching for file changes with StatReloader
2023-08-12 16:16:49,758 INFO [django.utils.autoreload:266] autoreload 103 139625083448136 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:16:51,652 INFO [django.utils.autoreload:668] autoreload 105 140489386269512 Watching for file changes with StatReloader
2023-08-12 16:17:15,839 INFO [django.utils.autoreload:266] autoreload 105 140489386269512 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:17:18,023 INFO [django.utils.autoreload:668] autoreload 107 139839673412424 Watching for file changes with StatReloader
2023-08-12 16:17:57,757 INFO [django.utils.autoreload:266] autoreload 107 139839673412424 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:17:59,973 INFO [django.utils.autoreload:668] autoreload 109 140446292581192 Watching for file changes with StatReloader
2023-08-12 16:18:29,569 INFO [django.utils.autoreload:266] autoreload 109 140446292581192 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:18:31,588 INFO [django.utils.autoreload:668] autoreload 111 140237874420552 Watching for file changes with StatReloader
2023-08-12 16:18:33,712 ERROR [app.api.ViewEntity:35] ViewEntity 111 140237807618872 ViewEntity (get) error Erro on get Entities When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2023-08-12 16:18:33,714 ERROR [django.request:241] log 111 140237807618872 Internal Server Error: /app/entities
2023-08-12 16:18:46,958 ERROR [app.api.ViewEntity:35] ViewEntity 111 140237807618872 ViewEntity (get) error Erro on get Entities When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2023-08-12 16:18:46,959 ERROR [django.request:241] log 111 140237807618872 Internal Server Error: /app/entities
2023-08-12 16:19:19,437 INFO [django.utils.autoreload:266] autoreload 111 140237874420552 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:19:21,369 INFO [django.utils.autoreload:668] autoreload 114 140373953739592 Watching for file changes with StatReloader
2023-08-12 16:19:39,528 INFO [django.utils.autoreload:266] autoreload 114 140373953739592 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:19:41,489 INFO [django.utils.autoreload:668] autoreload 116 140065696332616 Watching for file changes with StatReloader
2023-08-12 16:19:44,481 ERROR [app.api.ViewEntity:35] ViewEntity 116 140065629530936 ViewEntity (get) error Erro on get Entities When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2023-08-12 16:19:44,483 ERROR [django.request:241] log 116 140065629530936 Internal Server Error: /app/entities
2023-08-12 16:20:18,589 INFO [django.utils.autoreload:266] autoreload 116 140065696332616 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:20:20,760 INFO [django.utils.autoreload:668] autoreload 119 139710345333576 Watching for file changes with StatReloader
2023-08-12 16:20:22,322 ERROR [app.api.ViewEntity:35] ViewEntity 119 139710278638392 ViewEntity (get) error Erro on get Entities When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2023-08-12 16:20:22,323 ERROR [django.request:241] log 119 139710278638392 Internal Server Error: /app/entities
2023-08-12 16:20:28,176 INFO [django.utils.autoreload:266] autoreload 119 139710345333576 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:20:30,461 INFO [django.utils.autoreload:668] autoreload 122 139999337720648 Watching for file changes with StatReloader
2023-08-12 16:20:32,094 ERROR [app.api.ViewEntity:35] ViewEntity 122 139999270972216 ViewEntity (get) error Erro on get Entities name '_EntitySerializer__get_address_entities' is not defined
2023-08-12 16:20:32,096 ERROR [django.request:241] log 122 139999270972216 Internal Server Error: /app/entities
2023-08-12 16:20:37,975 INFO [django.utils.autoreload:266] autoreload 122 139999337720648 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:20:40,257 INFO [django.utils.autoreload:668] autoreload 125 140256587602760 Watching for file changes with StatReloader
2023-08-12 16:20:46,603 INFO [django.utils.autoreload:266] autoreload 125 140256587602760 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:20:48,703 INFO [django.utils.autoreload:668] autoreload 127 140618163383112 Watching for file changes with StatReloader
2023-08-12 16:20:52,563 ERROR [app.api.ViewEntity:35] ViewEntity 127 140618096601912 ViewEntity (get) error Erro on get Entities When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2023-08-12 16:20:52,566 ERROR [django.request:241] log 127 140618096601912 Internal Server Error: /app/entities
2023-08-12 16:23:04,467 INFO [django.utils.autoreload:266] autoreload 127 140618163383112 /application/app/serializer/EntitySerializer.py changed, reloading.
2023-08-12 16:23:07,025 INFO [django.utils.autoreload:668] autoreload 130 140090804341576 Watching for file changes with StatReloader
2023-08-12 16:23:11,538 ERROR [app.api.ViewEntity:35] ViewEntity 130 140090737531704 ViewEntity (get) error Erro on get Entities When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2023-08-12 16:23:11,539 ERROR [django.request:241] log 130 140090737531704 Internal Server Error: /app/entities
